apiVersion: v1
kind: ConfigMap
metadata:
  name: member-config
data:
  database.url: "jdbc:postgresql://postgres:5432/memberdb"
  spring.application.name: "member-service"
  trip.service.url: "http://trip-service:8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trip-config
data:
  database.url: "jdbc:postgresql://postgres:5432/tripdb"
  spring.application.name: "trip-service"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traveler-config
data:
  database.url: "jdbc:postgresql://postgres:5432/travelerdb"
  spring.application.name: "traveler-service" 